/* Choose the appropriated agent to run the pipeline */
node ('docker.kbulix.slave') {
    def app

    stage('checkout') {
        /* Let's make sure the repository cloned to Jenkins Workspace */
        checkout scm
        slackNotify channel: '#general', message: 'Starting Jenkins pipeline for web-express application.'
    }

    stage('build') {
        /* This builds the actual image */
        app = docker.build("kbulix/web-express")
        slackNotify channel: '#general', message: 'web-express build phase complete.'
    }

    stage('release') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }

        slackNotify channel: '#general', message: 'web-express release phase complete.'
    }
}
