apiVersion: v1
kind: Service
metadata:
  name: jenkins-orchestrator
spec:
  ports:
  - port: 8080
    name: webui
  - port: 50000
    name: agent-request
  selector:
    app: jenkins
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-orchestrator
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: jenkins:latest
        name: jenkins-orchestrator
        ports:
        - containerPort: 50000
          name: agent-request
        - containerPort: 8080
          name: webui
        volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /var/jenkins_home/
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-home-claim
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
